# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb6bbfefb5b6b64eca7aef891cded1280fc70fe9c3a455dd56ff21ac7cb3ed99065add4477eaa9f5fce1a10f1b4772ee9b6dd1e4e96c0a1f2216e46add95c2f2

test:
  secret_key_base: 5869ffc673f00963d6811bdafb379be18f77b1295e8c22a9e5bde15a7e1ac7376ee0ce3410f9f87368e1a202415a4a763de5dbe10eaafc54524c0b31ca98c613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
